// components/Copyright.tsx
import React from "react"

const Copyright = () => {
  const currentYear = new Date().getFullYear()

  return (
    <div className="flex justify-center my-4 font-light">
      <span className="font-semibold text-red-500 lowercase">josegpt</span>{" "}
      &copy; 1992 &mdash; {currentYear}
    </div>
  )
}

export default Copyright

// components/Copyright.vue
<template>
  <div class="flex flex-col items-center justify-center my-4 space-x-2 space-y-1 text-xs font-medium sm:flex-row sm:space-y-0 sm:text-base">
    <div>
      <span class="font-semibold text-red-500 lowercase">&copy; {{ $t("username") }}</span>
    <span>1992 &bullet; {{ currentYear }}</span>.
    </div>
    <span class="capitalize">{{ $t("allRightsReserved") }}</span>
  </div>
</template>

<script lang="ts">
import Vue from "vue"

export default Vue.extend({
  name: "Copyright",
  computed: {
    currentYear(): number {
      const now = new Date()

      return now.getFullYear()
    },
  },
})
</script>
