// components/SocialNetwork.tsx
import React from "react"
import Icon from "./Icon"

interface iSocialNetworkItem {
  link: string
  iconName: string
}

function SocialNetworkItem({
  link,
  iconName,
}: iSocialNetworkItem): JSX.Element {
  return (
    <a
      href={link}
      target="_blank"
      rel="noreferrer"
      className="flex items-center justify-center p-3 m-1 text-red-500 bg-red-200 rounded-full hover:bg-red-500 hover:text-gray-200"
    >
      <Icon name={iconName} />
    </a>
  )
}

interface iSocialNetwork {
  socialNetwork: iSocialNetworkItem[]
}

function SocialNetwork({ socialNetwork }: iSocialNetwork): JSX.Element {
  return (
    <section className="flex flex-wrap justify-center m-4">
      {socialNetwork.map((element) => (
        <SocialNetworkItem
          key={element.iconName}
          link={element.link}
          iconName={element.iconName}
        />
      ))}
    </section>
  )
}

export default SocialNetwork

// components/SocialNetwork.vue
<template>
  <a
    :href="href"
    target="_blank"
    rel="noreferrer"
    class="flex items-center justify-center w-10 h-10 mx-2 my-1 text-red-500 transition duration-300 ease-in-out bg-red-100 rounded-full hover:text-white hover:bg-red-500 dark:bg-red-900 dark:text-red-500 dark:hover:text-black dark:hover:bg-red-500"
  >
    <Icon :name="iconName" />
  </a>
</template>

<script lang="ts">
import Vue from "vue"

export default Vue.extend({
  name: "SocialNetwork",
  props: {
    href: {
      type: String,
      required: true,
    },
    iconName: {
      type: String,
      required: true,
    },
  },
})
</script>
