// components/Title.tsx
import React from "react"

interface iTitle {
  text: string
}

function Title({ text }: iTitle): JSX.Element {
  return (
    <h1 className="block -m-6 font-bold tracking-wider capitalize text-7xl sm:text-8xl">
      {text}
    </h1>
  )
}

export function Subtitle({ text }: iTitle): JSX.Element {
  return (
    <h2 className="block text-lg font-semibold tracking-wider text-red-500 lowercase sm:text-xl">
      {text}
    </h2>
  )
}

export default Title

// components/Title.vue
<template>
  <h1 class="flex flex-col text-center">
    <span class="font-semibold capitalize text-7xl sm:text-8xl">
      {{ title }}
    </span>
    <span
      class="-mt-1 text-lg tracking-wider text-red-500 lowercase sm:text-2xl"
    >
      {{ subtitle }}
    </span>
  </h1>
</template>

<script lang="ts">
import Vue from "vue"

export default Vue.extend({
  name: "Title",
  props: {
    title: {
      type: String,
      required: true,
    },
    subtitle: {
      type: String,
      required: true,
    },
  },
})
</script>
