// pages/index.vue
<template>
  <section class="flex items-center justify-center flex-grow">
    <Title :title="$t('name')" :subtitle="$t('profession')" />
  </section>
</template>

<script lang="ts">
import Vue from "vue"
import Title from "~/components/Title.vue"

export default Vue.extend({
  name: "Index",
  components: {
    Title,
  },
  async fetch() {
    this.$store.commit("setError", "")

    try {
      const response = await this.$axios.get(
        "https://api.github.com/users/josegpt/repos"
      )
      this.$store.commit("setProjects", response.data)
    } catch {
      this.$store.commit("setError", "there was an error getting the projects")
    }
  },
})
</script>

// pages/index.tsx
import axios from "axios"

import Projects from "../components/Projects"

const Index = ({ repository, isMenuOpen, hideMenu }) => (
  <div>
    <h1 className="font-semibold capitalize text-7xl sm:text-8xl">jose g</h1>
    <h2 className="-mt-2 text-xl tracking-wider text-center text-red-500 lowercase">
      software engineer
    </h2>
    <Projects repository={repository} isOpen={isMenuOpen} hideMenu={hideMenu} />
  </div>
)

export const getStaticProps = async () => {
  try {
    const { data } = await axios.get(
      "https://api.github.com/users/josegpt/repos"
    )
    return {
      props: { repository: { projects: data, err: null } },
    }
  } catch (err) {
    return { props: { repository: { projects: [], err } } }
  }
}

export default Index
